### ISSUE TITLE
三中捕获方式都无法显示图像

### ISSUE THREAD

**Issue by amberkell** [huiyadanli/bettergi-docs#1]
win11系统，奇怪的是圣遗物快捷键可用，其他的完全不可用，自动拾取也没有剧情日志

**Comment by huiyadanli** [comment]
首先以管理员权限启动，其次关闭安全软件。如果还是不行的话，尝试以下方案：

Win11下 BitBlt截图方式不可用的解决方法：

通过软件内直接跳转设置
![image](https://github.com/huiyadanli/bettergi-docs/assets/15783049/4f161ebc-207d-4a8f-90dc-9b70760cad6a)


查找Yuanshen（国际服Genshin），点击选项，并勾选不使用窗口化游戏优化

![image](https://github.com/huiyadanli/bettergi-docs/assets/15783049/3430b888-1ce6-4279-887b-0503abd15c0d)

然后重启游戏和软件，重新试试BitBlt截图方式
