### ISSUE TITLE
JS脚本运行失败

### ISSUE THREAD

**Issue by kkkkkd7** [huiyadanli/bettergi-docs#19]
运行调度器后，发生异常，想问问有没有什么解决办法
![屏幕截图 2024-10-18 124328](https://github.com/user-attachments/assets/2b786ae9-72cc-46e0-a7d8-4f126ce91743)

**Comment by huiyadanli** [comment]
需要在调度器内右键设置参数。如果还是报错，请卸载清除整个 BetterGI 的数据并重新安装后重试

**Comment by huiyadanli** [comment]
你确定是0.35版本？

**Comment by kkkkkd7** [comment]
> 你确定是0.35版本？

是的

**Comment by kkkkkd7** [comment]
切换截图模式后解决了，估计因为我是win11
