### ISSUE TITLE
自动拾取添加黑名单还是会自动点击

### ISSUE THREAD

**Issue by Xie-YaNing** [huiyadanli/bettergi-docs#5]
发现问题的原因是我在 永恒绿洲 地区做任务会自动点击 {激活回忆} 添加白名单并重启软件仍然会自动点击 {激活回忆}
![PixPin_2024-01-24_19-43-41](https://github.com/huiyadanli/bettergi-docs/assets/82919051/0a6eca5c-a655-48dd-963b-b50139d03f31)

**Comment by huiyadanli** [comment]
看左下的日志，是否是“激活回忆”。OCR识别可能有错的
